### ISSUE TITLE
Add Solution to backspace-string-compare - Leetcode

### ISSUE THREAD

**Issue by samyakjain10** [samyakjain10/LeetCode#4]

**Comment by rishuyadav** [comment]
Hey @samyakjain10 I would love to work on this issue, can u please assign it to me

**Comment by samyakjain10** [comment]
Add the solution and attach a screenshot in the description while making a pr

**Comment by rishuyadav** [comment]
Hey @samyakjain10 I have added the solution with screenshot as mentioned, please merge 
Thanks
