### ISSUE TITLE
Add Solution to complex-number-multiplication - Leetcode

### ISSUE THREAD

**Issue by samyakjain10** [samyakjain10/LeetCode#7]

**Comment by siddharthbihani** [comment]
I would like to work on this issue

**Comment by rishuyadav** [comment]
Hey @samyakjain10 I would like to take up this issue, can u please assign it to me.

**Comment by samyakjain10** [comment]
Add the solution and attach a screenshot in the description while making a PR.

**Comment by rishuyadav** [comment]
> Add the solution and attach a screenshot in the description while making a PR.

Screenshot of Leetcode Question or solution?

**Comment by samyakjain10** [comment]
Screenshot of accepted solution.

**Comment by rishuyadav** [comment]
Done Please merge @samyakjain10

**Comment by rishuyadav** [comment]
Hey @samyakjain10 Can u please add the 'Hacktoberfest accepted' label to my merged Prs, its not being displayed in my progress on the portal
