### ISSUE TITLE
Add Solution to construct-binary-tree-from-preorder-and-inorder-traversal - Leetcode

### ISSUE THREAD

**Issue by samyakjain10** [samyakjain10/LeetCode#8]

**Comment by siddharthbihani** [comment]
I would like to work on this issue

**Comment by rishuyadav** [comment]
Hey @samyakjain10  I have created a PR referencing this issue, please consider and merge, but it's failing semantic checks would it be a problem in merging.
Please accept under hactoberfest, Thanks

**Comment by samyakjain10** [comment]
Hey @rishuyadav. This issue is already assigned. You can work on some other issue or create a issue of your own and work on it.
